name: Validate Push
on:
  push:
    branches:    
      - master

defaults:
  run:
    shell: bash
    working-directory: project

jobs:
  validate-all-and-build:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project
      # checkout schema as xmllint can't https 
      - name: Checkout schema repo
        uses: actions/checkout@v3
        with:
          repository: BetaMasaheft/Schema
          path: schema
      - name: Install Test Dependencies
        run: sudo apt-get install libxml2-utils
      - name: Gather all source files
        id: all
        run: |
          echo "::set-output name=files::$( \
            find . -type f -name '*.xml' \
            -not -name 'build.xml' \
            -not -name 'repo.xml' \
            -not -name 'expath-pkg.xml' | \
            xargs \
          )"
      - name: Validate all source files
        run: |
          xmllint \
            --noout --xinclude --nowarning \
            --relaxng ../schema/tei-betamesaheft.rng \
            ${{ steps.all.outputs.files }} \
            2>&1 | \
            { grep -vE 'RNG|validates' || :; }
      - name: Build Expath Package
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - run: ant  

